# -*-coding:UTF-8-*-
# import pyodbc
import psycopg2

# mydb = pyodbc.connect('Driver={SQL Server};'
#                       'Server=CreditDB.mssql.somee.com;'
#                       'Integrated_Security=false;'
#                       'Database=CreditDB;'
#                       'Trusted_Connection=no;'
#                       'UID=Flubber_SQLLogin_1;'
#                       'PWD=l2hwi6n8ic;')
import Constant_File

mydb = psycopg2.connect(Constant_File.DB_URI, sslmode='require')

def CreateTable():
    mycursor = mydb.cursor()
    mycursor.execute('''
        CREATE TABLE IF NOT EXISTS CHATS (
            ChatId BIGINT PRIMARY KEY,
            CountUsers BIGINT ); ''')
    mydb.commit()
#     mycursor.execute('''
#     IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'PERSONS')
#      CREATE TABLE PERSONS (
#         PersonId BIGINT PRIMARY KEY,
#         ChatId BIGINT,
#         Name NVARCHAR(255) NOT NULL,
#         Credit NVARCHAR(255) NOT NULL
#         CONSTRAINT FK_PERSONS_To_CHATS FOREIGN KEY (ChatId) REFERENCES CHATS (ChatId)
# );
#                ''')

    mycursor.execute('''
        CREATE TABLE IF NOT EXISTS PERSONS (
            PersonId BIGINT PRIMARY KEY,
            ListChatId VARCHAR(255) NOT NULL,
            Name VARCHAR(255) NOT NULL,
            UserName VARCHAR(255) NOT NULL );
                   ''')
    mydb.commit()
    mycursor.execute('''
            CREATE TABLE IF NOT EXISTS
              DEBTS (
                DebtId INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                DebtValue FLOAT NOT NULL,
                PersonId BIGINT,
                ChatId BIGINT,
                PayerUserName VARCHAR(255) NOT NULL,
                CONSTRAINT FK_PersonDebt1 FOREIGN KEY (PersonId) REFERENCES PERSONS(PersonId),
                CONSTRAINT FK_PersonDebt2 FOREIGN KEY (ChatId) REFERENCES CHATS(ChatId)
        );
                       ''')
    mydb.commit()
    mycursor.execute('''
            CREATE TABLE IF NOT EXISTS
              CARDS (
                CardId INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                CardValue VARCHAR(255) NOT NULL,
                PersonId BIGINT,
                ChatId BIGINT,
                CONSTRAINT FK_PersonCard1 FOREIGN KEY (PersonId) REFERENCES PERSONS(PersonId),
                CONSTRAINT FK_PersonCard2 FOREIGN KEY (ChatId) REFERENCES CHATS(ChatId)
        );
                       ''')
    mydb.commit()
    mycursor.close()


def AddChatId(PersonId, ChatId):
    mycursor = mydb.cursor()
    mycursor.execute(f'''SELECT ListChatId
    FROM PERSONS
    WHERE PersonId = {PersonId}''')
    ListChatId = mycursor.fetchone()[0] + str(ChatId) + ';'
    print(ListChatId)
    query = f'''UPDATE PERSONS
    Set ListChatId = '{ListChatId}' WHERE PersonId = {PersonId} '''
    mycursor.execute(query)
    mydb.commit()
    mycursor.execute(f'''SELECT CountUsers
    FROM CHATS
    WHERE ChatId = {ChatId}''')
    CountUsers = mycursor.fetchone()[0] + 1
    print(CountUsers)
    print(ListChatId)
    mycursor.execute(f'''UPDATE CHATS
    Set CountUsers = {CountUsers}
    WHERE ChatId = {ChatId} ''')
    mydb.commit()
    mycursor.close()


def IfChatExists(PersonId, ChatId):
    mycursor = mydb.cursor()
    mycursor.execute(f'''
        SELECT * FROM PERSONS WHERE PersonId = {PersonId}
    ''')
    StringChatId = str(mycursor.fetchone()[1])
    ListChatId = StringChatId.split(';')
    for el in ListChatId:
        if str(ChatId) == el:
            mycursor.close()
            return True
    mycursor.close()
    return False


def CheckUser(PersonId, ChatId):
    mycursor = mydb.cursor()
    mycursor.execute(f'''SELECT COUNT(*) FROM PERSONS Where PersonId = {PersonId}
    ''')
    if mycursor.fetchone()[0] == 1:
        if IfChatExists(PersonId, ChatId):
            return True
    return False


def CheckUserByUserName(UserName, ChatId):
    mycursor = mydb.cursor()
    mycursor.execute(f'''SELECT COUNT(*) FROM PERSONS WHERE UserName = N'{UserName}' ''')
    if mycursor.fetchone()[0] == 1:
        PersonId = getUserIdByUserName(UserName)
        if IfChatExists(PersonId, ChatId):
            return True
    return False


def CheckCardDoubleInfo(PersonId, ChatId, CardValues):
    if CheckCard(PersonId, ChatId):
        mycursor = mydb.cursor()
        mycursor.execute(f'''SELECT * FROM CARDS Where PersonId = {PersonId} AND ChatId = {ChatId}''')
        info = str(mycursor.fetchone()[1])
        if CardValues in info:
            return True
        else:
            return False
    return False


def CheckCardPersonsDoubleInfo(PersonId, ChatId, CardValues):
    if CheckCard(PersonId, ChatId):
        mycursor = mydb.cursor()
        mycursor.execute(f'''SELECT * FROM CARDS Where ChatId = {ChatId}''')
        for row in mycursor.fetchall():
            # print(row)
            if CardValues in row[1]:
                if not row[2] == PersonId:
                    return True
    return False


def CheckCard(PersonId, ChatId):
    mycursor = mydb.cursor()
    mycursor.execute(f'''SELECT COUNT(*) FROM CARDS Where PersonId = {PersonId} AND ChatId = {ChatId}
    ''')
    if mycursor.fetchone()[0] == 1:
        if IfChatExists(PersonId, ChatId):
            return True
    return False


def GetUsersFromCurrChat():
    mycursor = mydb.cursor()
    mycursor.execute(f'''
        SELECT * FROM PERSONS
    ''')
    return mycursor.fetchall()


def GetChats(PersonId, ChatId):
    mycursor = mydb.cursor()
    mycursor.execute(f'''
        SELECT * FROM PERSONS WHERE PersonId = {PersonId}'
    ''')
    StringChatId = str(mycursor[1])
    ListChatId = StringChatId.split(';')
    return ListChatId


def GetCard(PersonId,ChatId):
    mycursor = mydb.cursor()
    mycursor.execute(f'''
        SELECT * FROM CARDS WHERE PersonId = {PersonId} AND ChatId = {ChatId}
    ''')
    info = mycursor.fetchone()
    print(info)
    if info is None:
        return "Не додано"
    else:
        if info[1] == "":
            return "Не додано"
        else:
            return info[1]


def CheckLoneLinnes(PersonId,ChatId):
    CreateChat(ChatId)
    mycursor = mydb.cursor()
    mycursor.execute(f'''
           SELECT CountUsers FROM CHATS WHERE ChatId = {ChatId}
       ''')
    CountUsers = mycursor.fetchone()[0]
    print(CountUsers)
    if CountUsers == 1:
        return "Ти скидаєшся сам з собою, знайди собі друзів"
    elif CountUsers == 0:
        return 'Для початку увійдіть в гільдію: команда /entertheparty'
    return False


def AddDebtForAll(PersonId,ChatId,DebtValue):
    mycursor = mydb.cursor()
    mycursor.execute(f'''
           SELECT CountUsers FROM CHATS WHERE ChatId = {ChatId}
       ''')
    CountUsers = mycursor.fetchone()[0]
    print("base: " + CountUsers)
    mycursor.execute(f'''
                    SELECT * FROM PERSONS
                ''')
    list = mycursor.fetchall()
    for row in list:
        if CheckUser(row[0], ChatId) and row[0] == PersonId:
            UserNamePayer = row[3]
            print("UserName: " + UserNamePayer)
            break
    for row in list:
        if CheckUser(row[0], ChatId) and not row[0] == PersonId:
            print("UserName: " + UserNamePayer)
            print("CountUsers: " + str(CountUsers))
            AddDebt(UserNamePayer, row[0], ChatId, DebtValue / CountUsers)
        else:
            continue


def AddDebtForGroupNotAll(PersonId,ChatId,DebtValue,listPerson):
    mycursor = mydb.cursor()
    mycursor.execute(f'''
                    SELECT * FROM PERSONS
                ''')
    list = mycursor.fetchall()
    for row in list:
        if CheckUser(row[0], ChatId) and row[0] == PersonId:
            UserNamePayer = row[3]
            print("UserName: " + UserNamePayer)
            break
    for row in listPerson:
        if not getUserIdByUserName(row) == PersonId:
            print("row: " + row)
            AddDebt(UserNamePayer, getUserIdByUserName(row), ChatId, float(DebtValue) / float(len(listPerson)))


def AddDebtForOne(PayerId,ChatId,DebtValue,PersonId):
    mycursor = mydb.cursor()
    mycursor.execute(f'''
                    SELECT * FROM PERSONS
                ''')
    list = mycursor.fetchall()
    for row in list:
        if CheckUser(PayerId, ChatId) and row[0] == PayerId:
            UserNamePayer = row[3]
            break
    if not PayerId == PersonId:
        print("PersonId: " + str(PersonId))
        AddDebt(UserNamePayer, PersonId, ChatId, DebtValue)


def AddDebt(PayerUserName,PersonId,ChatId,DebtValue):
    mycursor = mydb.cursor()
    insert_query_debt = f'''INSERT INTO DEBTS (DebtValue, PersonId , ChatId, PayerUserName)
    SELECT {DebtValue}, {PersonId}, {ChatId}, '{PayerUserName}'
    WHERE NOT EXISTS ( SELECT * FROM DEBTS WHERE ChatId = {ChatId} AND PersonId = {PersonId} AND PayerUserName = N'{PayerUserName}') '''
    mycursor.execute(insert_query_debt)
    mydb.commit()
    mycursor.execute(f'''SELECT DebtValue FROM DEBTS WHERE PersonId = {PersonId} AND ChatId = {ChatId} AND PayerUserName = N'{PayerUserName}' ''')
    DebtValue = mycursor.fetchone()[0] + float(DebtValue)
    mycursor.execute(f'''UPDATE DEBTS
    SET DebtValue = {DebtValue}
    WHERE PersonId = {PersonId} AND ChatId = {ChatId} AND PayerUserName = N'{PayerUserName}' ''')
    mydb.commit()
    mycursor.close()


def GetDebt(PersonId,ChatId):
    mycursor = mydb.cursor()
    mycursor.execute(f'''SELECT * FROM DEBTS WHERE ChatId = {ChatId} AND PersonId = {PersonId}''')
    debtList = mycursor.fetchall()
    debtInfo = ""
    for row in debtList:
        debtInfo += str(round(row[1],3)) + " грн" + " Кому: " + '@' + str(row[4]) + '\n'
    mycursor.close()
    return debtInfo


def CheckMinusDebt(PersonId, ChatId, DebtValue, PayerUserName):
        mycursor = mydb.cursor()
        mycursor.execute(f'''SELECT * FROM DEBTS Where ChatId = {ChatId} AND PersonId = {PersonId} AND PayerUserName = N'{PayerUserName}' ''')
        debt = mycursor.fetchone()[1]
        if debt - DebtValue < 0:
            return True
        return False


def CheckIfZeroDebt(PersonId, ChatId, PayerUserName):
    mycursor = mydb.cursor()
    mycursor.execute(
        f'''SELECT * FROM DEBTS Where ChatId = {ChatId} AND PersonId = {PersonId} AND PayerUserName = N'{PayerUserName}' ''')
    debt = mycursor.fetchone()[1]
    if debt == 0:
        return True
    return False


def CheckMinusDebtByAdding(PersonId, ChatId, DebtValue, PayerUserName):
        mycursor = mydb.cursor()
        mycursor.execute(
            f'''SELECT * FROM DEBTS Where ChatId = {ChatId} AND PersonId = {PersonId} AND PayerUserName = N'{PayerUserName}' ''')
        debt = mycursor.fetchone()[1]
        if debt + DebtValue < 0:
            return True
        return False


def RemoveExactDebt(PersonId, ChatId, DebtValueCurr, PayerUserName):
    mycursor = mydb.cursor()
    mycursor.execute(
        f'''UPDATE DEBTS
        SET DebtValue = DebtValue - {DebtValueCurr}
        Where ChatId = {ChatId} AND PersonId = {PersonId} AND PayerUserName = N'{PayerUserName}' ''')
    mydb.commit()
    mycursor.close()


def RemoveDebt(PersonId,ChatId,PayerUserName):
    mycursor = mydb.cursor()
    mycursor.execute(f'''UPDATE DEBTS
    SET DebtValue = {0}
    WHERE PersonId = {PersonId} AND ChatId = {ChatId} AND PayerUserName = N'{PayerUserName}' ''')
    mydb.commit()
    mycursor.close()



def getUserIdByUserName(UserName):
    mycursor = mydb.cursor()
    mycursor.execute(f'''SELECT PersonId FROM PERSONS WHERE UserName = N'{UserName}' ''')
    userId = mycursor.fetchone()[0]
    print(userId)
    return userId



def checkIfPersonHaveDebtFromPayer(PersonUserName, ChatId, PayerUserName):
    mycursor = mydb.cursor()
    if CheckUserByUserName(PersonUserName, ChatId):
        PersonId = getUserIdByUserName(PersonUserName)
        mycursor.execute(
            f'''SELECT COUNT(*) FROM DEBTS Where ChatId = {ChatId} AND PersonId = {PersonId} AND PayerUserName = N'{PayerUserName}' ''')
        countOfExistance = mycursor.fetchone()[0]
        if countOfExistance == 1:
            return True
    return False



def CreateChat(ChatId):
    mycursor = mydb.cursor()
    mycursor.execute(f'''
        INSERT INTO CHATS (ChatId,CountUsers)
        SELECT {ChatId}, {0}
        WHERE NOT EXISTS ( SELECT * FROM CHATS WHERE ChatId = {ChatId}) ''')
    mydb.commit()
    mycursor.close()


def DeleteCards(message):
    mycursor = mydb.cursor()
    mycursor.execute(f'''UPDATE CARDS SET CardValue = '' WHERE PersonId = {str(message.from_user.id)} AND ChatId = {str(message.chat.id)}''')
    mydb.commit()
    mycursor.close()


def AddCard(ChatId,PersonId,CardValues):
        mycursor = mydb.cursor()
        mycursor.execute(f'''SELECT COUNT(*) FROM CARDS WHERE ChatId = {ChatId} AND PersonId = {PersonId}''')
        backslach = '\n'
        if mycursor.fetchone()[0] == 1:
            mycursor.execute(f'''SELECT CardValue FROM CARDS WHERE PersonId = {PersonId} AND ChatId = {ChatId}''')
            CardValue = mycursor.fetchone()[0] + backslach + CardValues
            mycursor.execute(f'''UPDATE CARDS
            SET CardValue = '{CardValue}'
            WHERE PersonId = {PersonId} AND ChatId = {ChatId}''')
            mydb.commit()
        else:
            insert_query_card = f'''
                INSERT INTO CARDS (CardValue,PersonId,ChatId)
                SELECT '{backslach}{CardValues}',{PersonId},{ChatId}
                WHERE NOT EXISTS ( SELECT * FROM CARDS WHERE ChatId = {ChatId} AND PersonId = {PersonId}) '''
            mycursor.execute(insert_query_card)
            mydb.commit()
        mycursor.close()


def InsertData(ChatId, PersonId, FullName, UserName):
    CreateChat(ChatId)
    mycursor = mydb.cursor()
    mycursor.execute(f'''
        INSERT INTO PERSONS (PersonId, ListChatId, Name, UserName)
        SELECT {PersonId},'',N'{FullName}',N'{UserName}'
        WHERE
         NOT EXISTS ( SELECT * FROM PERSONS WHERE PersonId = {PersonId}) ''')
    mydb.commit()
    # insert_query_debt = f'''
    #     IF NOT EXISTS ( SELECT * FROM DEBTS WHERE PersonId = {PersonId} AND ChatId = {ChatId})
    #         INSERT INTO DEBTS (DebtValue, PersonId , ChatId, PayerUserName)
    #         VALUES (?,?,?,?);'''
    # values_debt = (0, PersonId, ChatId, '')
    # mycursor.execute(insert_query_debt, values_debt)
    # mydb.commit()
    if not IfChatExists(PersonId, ChatId):
        AddChatId(PersonId,ChatId)
    mycursor.close()


def ShowData(message):
    users = ""
    ListChatId = []
    PersonId = message.from_user.id
    ChatId = message.chat.id
    mycursor = mydb.cursor()
    mycursor.execute(f'''
        INSERT INTO CHATS (ChatId)
        SELECT {ChatId}
    WHERE 
        NOT EXISTS ( SELECT * FROM CHATS WHERE ChatId = {ChatId}) ''')
    mydb.commit()
    for row in GetUsersFromCurrChat():
        if IfChatExists(row[0],ChatId):
            users += "Шо за мужик : @"
            users += str(row[3])
            users += "\n"
            users += "Реквізити: "
            users += str(GetCard(row[0],ChatId))
            users += "\n"
            users += "|| Борг: "
            users += str(GetDebt(row[0],ChatId))
            users += "\n"
            # print(row)
    # print(users)
    if users == "":
        users = "Наразі учасників ще немає"
    mycursor.close()
    return users

def ShowChats():
    mycursor = mydb.cursor()
    mycursor.execute('''SELECT * FROM CHATS''')
    for row in mycursor:
        print(row)
    mydb.commit()
    mycursor.close()

def DeleteData():
    mycursor = mydb.cursor()
    mycursor.execute('''DROP TABLE DEBTS''')
    mycursor.execute('''DROP TABLE CARDS''')
    mycursor.execute('''DROP TABLE PERSONS''')
    mycursor.execute('''DROP TABLE CHATS''')
    mydb.commit()
    mycursor.close()